@php $e = $expense ?? null; $categories = $categories ?? collect(); @endphp
<div class="row g-3">
    <div class="col-md-4 apc-field"><label class="apc-label">Tanggal <span class="text-danger">*</span></label><input type="date" name="date" value="{{ old('date', $e?->date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" class="apc-input" required></div>
    <div class="col-md-4 apc-field"><label class="apc-label">Kategori</label><select name="expense_category_id" class="apc-select"><option value="">—</option>@foreach($categories as $c)<option value="{{ $c->id }}" {{ old('expense_category_id', $e?->expense_category_id) == $c->id ? 'selected' : '' }}>{{ $c->name }}</option>@endforeach</select></div>
    <div class="col-md-4 apc-field"><label class="apc-label">Metode</label><select name="payment_method" class="apc-select">@foreach(\App\Models\Payment::METHODS as $k => $v)<option value="{{ $k }}" {{ old('payment_method', $e?->payment_method ?? 'cash') === $k ? 'selected' : '' }}>{{ $v }}</option>@endforeach</select></div>
    <div class="col-12 apc-field"><label class="apc-label">Deskripsi <span class="text-danger">*</span></label><input type="text" name="description" value="{{ old('description', $e?->description) }}" class="apc-input" required></div>
    <div class="col-md-6 apc-field"><label class="apc-label">Jumlah <span class="text-danger">*</span></label><input type="number" name="amount" value="{{ old('amount', $e?->amount) }}" class="apc-input" min="1" required></div>
    <div class="col-md-6 apc-field"><label class="apc-label">Referensi</label><input type="text" name="reference" value="{{ old('reference', $e?->reference) }}" class="apc-input"></div>
    <div class="col-12 apc-field"><label class="apc-label">Catatan</label><textarea name="notes" rows="2" class="apc-textarea">{{ old('notes', $e?->notes) }}</textarea></div>
</div>